# Generated by Django 3.2.3 on 2021-06-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_meetup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='location',
        ),
    ]
