# Generated by Django 3.2.3 on 2021-06-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20210623_0233'),
        ('meetups', '0008_remove_meetup_location'),
    ]

    operations = [
    ]
