# Generated by Django 3.2.3 on 2021-06-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0010_auto_20210623_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=100)),
                ('orgEmail', models.EmailField(max_length=254)),
                ('orgDate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetups.organizer'),
            preserve_default=False,
        ),
    ]
