# Generated by Django 3.2.3 on 2021-06-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0009_merge_20210623_0912'),
        ('meetups', '0011_auto_20210623_0510'),
    ]

    operations = [
    ]
