# Generated by Django 3.2.3 on 2021-06-23 03:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0012_merge_20210623_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='orgContact',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
