# Generated by Django 3.2.3 on 2021-06-23 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0014_alter_organizer_orgcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='orgContact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
